### ISSUE TITLE
asdsadsadsa

### ISSUE THREAD

**Issue by gillcosta** [MentallyFriendly/master-board#6]
## Acceptance Criteria 
- [ ] Please add one acceptance criteria here
- [ ] Please add one acceptance criteria here
- [ ] Add as many as needed

## Design

<img width="1088" alt="screen shot 2016-09-19 at 10 00 14" src="https://cloud.githubusercontent.com/assets/7959199/18775192/6dde59de-81a3-11e6-8082-4442df315eb8.png">
